# Generated by Django 3.1.6 on 2021-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='feature_photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
