# Generated by Django 3.1.6 on 2021-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_feature_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='feature_photo',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
