# Generated by Django 3.1.6 on 2021-05-19 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='images1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='images2',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
    ]
