# Generated by Django 3.1.6 on 2021-05-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210519_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('game_comment', models.CharField(max_length=150)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.comment')),
            ],
        ),
    ]
