# Generated by Django 3.1.6 on 2021-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='game_comment',
            field=models.CharField(max_length=200),
        ),
    ]
