# Generated by Django 3.1.6 on 2021-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
