# Generated by Django 3.1.6 on 2021-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
