# Generated by Django 3.1.6 on 2021-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20210521_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Action-adventure', 'Action-adventure'), ('Adventure', 'Adventure'), ('Role-playing', 'Role-playing'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
